Repository team-incube/GSMC-server-V2, pull requests merged in 2025-05, with the labels that each got.

#72 코드 내부 변수명 오탈자 수정
  src/main/java/team/incude/gsmc/v2/global/security/jwt/usecase/service/JwtParserService.java
Labels: 🛠️ 리팩터링

#75 회원가입 시 비관적 락 적용
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
Labels: 🔨 버그수정

#76 2025/05/01 7차 배포
  log/README.mdx
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificatePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/CertificatePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByCurrentUserAndTypeService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByFilteringByStudentCodeAndTitleAndTypeService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByStudentCodeAndFilteringTypeAndStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateActivityEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherEvidenceByCurrentuserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherScoringEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReadingEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReviewStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/EvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/CreateActivityEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/CreateReadingEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchActivityEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchReadingEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/MemberPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/exception/MemberInvalidException.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/MemberPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/error/ErrorCode.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/usecase/service/JwtParserService.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceServiceTest.java
Labels: 💾 일반배포

#77 ``NonUniqueResultException`` 예외 핸들링 추가
  src/main/java/team/incude/gsmc/v2/global/error/handler/GlobalExceptionHandler.java
Labels: ✨ 기능개발

#78 자격증 모델 클래스 주석추가
  src/main/java/team/incude/gsmc/v2/aspect/log/HttpLoggingAspect.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/CertificateApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificateApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificatePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/DeleteCertificateUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/FindCertificateUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/UpdateCurrentCertificateUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/UpdateCurrentCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/exception/CertificateNotBelongToMemberException.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/exception/CertificateNotFoundException.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/CertificateWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/GetCertificateDto.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/request/CreateCertificateRequest.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/request/PatchCertificateRequest.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/response/GetCertificateResponse.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/CertificatePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/mapper/CertificateMapper.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/projection/CertificateProjection.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/repository/CertificateJpaRepository.java
Labels: 📃 문서화

#81 유틸리티,매퍼,전역 예외처리,AWS S3 관련 인터페이스/클래스 JavaDoc 주석추가
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/S3Port.java
  src/main/java/team/incude/gsmc/v2/global/error/ErrorCode.java
  src/main/java/team/incude/gsmc/v2/global/error/data/response/ErrorResponse.java
  src/main/java/team/incude/gsmc/v2/global/error/exception/GsmcException.java
  src/main/java/team/incude/gsmc/v2/global/error/handler/GlobalExceptionHandler.java
  src/main/java/team/incude/gsmc/v2/global/mapper/GenericMapper.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/exception/S3DeleteFailedException.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/exception/S3UploadFailedException.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/S3Adapter.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/config/S3Config.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/usecase/FileDeleteUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/usecase/FileUploadUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/usecase/service/FileDeleteService.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/usecase/service/FileUploadService.java
  src/main/java/team/incude/gsmc/v2/global/util/ExtractFileKeyUtil.java
  src/main/java/team/incude/gsmc/v2/global/util/FileValidationUtil.java
  src/main/java/team/incude/gsmc/v2/global/util/SimulateScoreUtil.java
  src/main/java/team/incude/gsmc/v2/global/util/SnakeKebabToCamelCaseConverterUtil.java
  src/main/java/team/incude/gsmc/v2/global/util/ValueLimiterUtil.java
  src/main/java/team/incude/gsmc/v2/global/util/exception/EmptyFileException.java
  src/main/java/team/incude/gsmc/v2/global/util/exception/FileNameTooLongException.java
  src/main/java/team/incude/gsmc/v2/global/util/exception/InvalidFileUrlException.java
Labels: 📃 문서화

#86 설정 클래스 JavaDoc 주석추가
  src/main/java/team/incude/gsmc/v2/global/config/AspectConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/AsyncConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/CacheConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/PasswordEncoderConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/QueryDslConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/SchedulerConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/TimeZoneConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/TransactionConfig.java
Labels: 📃 문서화

#90 증빙자료 관련 임시 저장 조회 서비스 구현 및 score 생성 로직 구현
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/EvidenceApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/DraftActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/DraftReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidenceApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/FindDraftEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindDraftEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/domain/DraftActivityEvidence.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/domain/DraftReadingEvidence.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/domain/ReadingEvidence.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/DraftActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/DraftReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/entity/DraftActivityEvidenceRedisEntity.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/entity/DraftReadingEvidenceRedisEntity.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/repository/DraftActivityEvidenceRedisRepository.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/repository/DraftReadingEvidenceRedisRepository.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/response/GetDraftEvidenceResponse.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceServiceTest.java
Labels: ✨ 기능개발

#88 Auth 테스트 코드 작성
  src/main/java/team/incude/gsmc/v2/domain/auth/application/port/EmailPort.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/ChangePasswordUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/ChangePasswordService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/AuthApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/AuthWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/TokenResponse.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/FindAllStudentUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/FindCurrentStudentUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/FindStudentByStudentCodeUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/SearchStudentUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/EmailAdapter.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/application/usecase/EmailSendUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/usecase/EmailSendUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/usecase/service/EmailSendService.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/RefreshServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignInServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/VerifyEmailServiceTest.java
Labels: 🛠️ 리팩터링, ✨ 기능개발

#93 한자/한국사 자격증 등록 시 동시성 문제 해결
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificatePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/UpdateCurrentCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/exception/CertificateCategoryMismatchException.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/exception/DuplicateCertificateException.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/CertificatePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/error/ErrorCode.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/UpdateCurrentCertificateServiceTest.java
Labels: 🛠️ 리팩터링, 🔨 버그수정

#96 자격증 변동 시 종합 점수 계산 이벤트 발행 추가
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateService.java
Labels: 🛠️ 리팩터링

#97 증빙자료 score 엔티티 생성 로직 수정
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateDraftActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateDraftReadingEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceService.java
Labels: 🔨 버그수정

#95 단위테스트 수행 CI 구축
  .github/workflows/deploy-dev.yml
  .github/workflows/test-develop.yml
  Dockerfile
  build.gradle.kts
  docker-compose.test.yaml
  src/main/resources/application-test.yaml
Labels: 🏭 CI/CD

#98 테스트 변경사항 반영
  src/main/resources/application-test.yaml
  src/test/java/team/incude/gsmc/v2/GsmcApplicationTests.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateServiceTest.java
Labels: 🔨 버그수정, 🏭 CI/CD

#100 ``auth`` 및 이메일 관련 인터페이스/클래스 JavaDoc 주석추가
  src/main/java/team/incude/gsmc/v2/domain/auth/application/port/AuthCodePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/port/AuthenticationPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/port/EmailPort.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/ChangePasswordUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/RefreshUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/SendAuthenticationEmailUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/SignInUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/SignUpUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/VerifyEmailUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/ChangePasswordService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/RefreshService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignInService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/VerifyEmailService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/util/GenerationAuthCode.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/AuthenticationNotFoundException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/EmailAuthAttemptExceededException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/EmailFormatInvalidException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/MemberExistException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/MemberForbiddenException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/PasswordInvalidException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/RefreshTokenInvalidException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/exception/VerificationInvalidException.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/AuthApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/AuthCodePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/AuthenticationPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/mapper/AuthCodeMapper.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/mapper/AuthenticationMapper.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/repository/AuthCodeRedisRepository.java
  src/main/java/team/incude/gsmc/v2/domain/auth/persistence/repository/AuthenticationRedisRepository.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/AuthWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/request/ChangePasswordRequest.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/request/RefreshRequest.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/request/SendEmailRequest.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/request/SignInRequest.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/request/SignUpRequest.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/request/VerificationCodeRequest.java
  src/main/java/team/incude/gsmc/v2/domain/auth/presentation/data/response/AuthTokenResponse.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/EmailAdapter.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/config/EmailConfig.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/exception/EmailSendFailedException.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/usecase/EmailSendUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/usecase/service/EmailSendService.java
Labels: 📃 문서화

#103 Discord 임베드 알림 기능 추가
  .env.example
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/ChangePasswordService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/util/AuthCodeGenerator.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/EmbedColor.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/data/DiscordEmbed.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/data/DiscordField.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/data/DiscordWebhookPayload.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/service/DiscordApplicationLifecycleNotifyService.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/service/DiscordLogbackService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: ✨ 기능개발

#108 JwtPort 의존성 변경
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/RefreshServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignInServiceTest.java
Labels: 🔨 버그수정

#111 대기상태 증빙자료 여부 포함 사용자 조회 시 다건 조회 문제 수정
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
Labels: 🔨 버그수정

#112 상위 증빙자료 영속화 코드 추가
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
Labels: ✨ 기능개발

#114 임시 저장 증빙자료 삭제 시 예외 처리 추가
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/CreateDraftActivityEvidenceReqeust.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/CreateDraftReadingEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/DraftEvidenceDeleteEventListener.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceServiceTest.java
Labels: 🔨 버그수정

#117 카테고리 캐시 키 고정 키로 변경
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/CategoryPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/config/CacheConfig.java
Labels: 🔨 버그수정

#123 시트 생성 중 NPE 발생 문제 수정
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetService.java
  src/test/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetServiceTest.java
Labels: 🔨 버그수정
