Repository team-incube/GSMC-server-V2, pull requests merged in 2025-06, with the labels that each got.

#125 로깅방식 변경
  src/main/java/team/incude/gsmc/v2/aspect/log/HttpLoggingAspect.java
  src/main/java/team/incude/gsmc/v2/global/config/WebFilterConfig.java
  src/main/java/team/incude/gsmc/v2/global/filter/logging/HttpLoggingFilter.java
Labels: ✨ 기능개발

#121 학번을 이메일로 조작하는 AOP 클래스 구현
  src/main/java/team/incude/gsmc/v2/aspect/converter/StudentCodeEmailAspect.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReviewStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/MemberApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/MemberApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/MemberPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/FindStudentByEmailUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/service/FindStudentByEmailService.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/MemberPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/presentation/MemberWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/ScoreApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScoreApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/presentation/ScoreWebAdapter.java
  src/main/java/team/incude/gsmc/v2/global/event/ScoreUpdatedEvent.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/DraftEvidenceDeleteEventListener.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/ScoreUpdatedEventListener.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/member/application/usecase/service/FindStudentByEmailServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreServiceTest.java
Labels: ✨ 기능개발

#131 로깅 필터 관련 개선
  src/main/java/team/incude/gsmc/v2/global/filter/logging/HttpLoggingFilter.java
Labels: 🔨 버그수정, 📃 문서화

#137 증빙자료 삭제 서비스 클래스 수정
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
Labels: 🔨 버그수정

#139 회원가입 시 ``MemberInvalidException`` 오류 해결
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/MemberPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/security/config/SecurityConfig.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpServiceTest.java
Labels: 🔨 버그수정

#140 트랜젝션 커밋 전 이벤트 수신 문제 해결
  src/main/java/team/incude/gsmc/v2/global/event/handler/DraftEvidenceDeleteEventListener.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/ScoreUpdatedEventListener.java
Labels: 🔨 버그수정

#141 2025/06/18 14차 배포
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/MemberPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/DraftEvidenceDeleteEventListener.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/ScoreUpdatedEventListener.java
  src/main/java/team/incude/gsmc/v2/global/security/config/SecurityConfig.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpServiceTest.java
Labels: 💾 일반배포

#143 엔드포인트 접근 권한 설정
  src/main/java/team/incude/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
Labels: ✨ 기능개발

#145 선생님 접근 권한 추가
  src/main/java/team/incude/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
Labels: ✨ 기능개발

#147 2025/06/20 16차 배포
  src/main/java/team/incude/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
Labels: 💾 일반배포

#146 증빙자료 파일 업로드 성능 개선
  build.gradle.kts
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/EvidenceApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/DiscordPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidenceApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateEvidenceFileUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateDraftActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateDraftReadingEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateEvidenceFileService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/mapper/ActivityEvidenceMapper.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/mapper/ReadingEvidenceMapper.java
  src/main/java/team/incude/gsmc/v2/global/config/RetryConfig.java
  src/main/java/team/incude/gsmc/v2/global/event/FileUploadEvent.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/FileUploadEventListener.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/DiscordAdapter.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/service/SendEvidenceUploadFailureAlertUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/discord/service/impl/SendEvidenceUploadFailureAlertService.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
Labels: 🛠️ 리팩터링

#148 증빙자료 도메인 테스트 코드 수정
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
Labels: 🔨 버그수정

#151 Pull Request 템플릿에 ``RCA`` 규칙 관련 내용 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 문서화

#154 증빙자료 이미지 업로드 실패 시 재시도 큐 추가 및 수정 서비스 클래스 수정
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/EvidenceApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/consumer/RetryFileUploadConsumer.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidenceApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/RedisPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/RetryUploadZSetPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/RetryFileUploadUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateActivityEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateEvidenceFileUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateOtherEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateOtherScoringEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/RetryFileUploadService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateActivityEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateEvidenceFileService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherEvidenceByCurrentuserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherScoringEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/domain/RetryUploadCommand.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/FileUploadRetryMessageDto.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchActivityEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchOtherEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchOtherScoringEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/global/event/FileUploadEvent.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/FileUploadEventListener.java
  src/main/java/team/incude/gsmc/v2/global/redis/RedisAdapter.java
  src/main/java/team/incude/gsmc/v2/global/redis/RetryUploadZSetAdapter.java
  src/main/java/team/incude/gsmc/v2/global/redis/config/RedisConfig.java
  src/main/java/team/incude/gsmc/v2/global/redis/mapper/RetryUploadMapper.java
  src/main/java/team/incude/gsmc/v2/global/util/InputStreamUtil.java
  src/test/java/team/incude/gsmc/v2/domain/RetryFileUploadConsumerTest.java
  src/test/java/team/incude/gsmc/v2/domain/RetryFileUploadServiceTest.java
Labels: 🛠️ 리팩터링

#162 비밀번호 필드 길이 최소 제한 추가
  src/main/java/team/incube/gsmc/v2/domain/auth/presentation/data/request/ChangePasswordRequest.java
  src/main/java/team/incube/gsmc/v2/domain/auth/presentation/data/request/SignInRequest.java
  src/main/java/team/incube/gsmc/v2/domain/auth/presentation/data/request/SignUpRequest.java
Labels: 🔨 버그수정

#171 JavaDoc 누락 클래스/인터페이스 주석 추가
  src/main/java/team/incube/gsmc/v2/GsmcApplication.java
  src/main/java/team/incube/gsmc/v2/global/config/PropertiesScanConfig.java
  src/main/java/team/incube/gsmc/v2/global/config/RetryConfig.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/data/JwtEnvironment.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/data/TokenDto.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/persistence/entity/RefreshTokenRedisEntity.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/persistence/repository/RefreshTokenRedisRepository.java
  src/main/java/team/incube/gsmc/v2/global/thirdparty/aws/data/AwsEnvironment.java
Labels: 📃 문서화

#170 정기배포 Pull Request 자동생성 기능 구현
  .github/workflows/auto-deploy-pr.yml
Labels: 🏭 CI/CD

#172 2025/06/28 19차 배포
  .github/workflows/auto-deploy-pr.yml
  log/.gitkeeper
  log/README.mdx
  src/main/java/team/incube/gsmc/v2/GsmcApplication.java
  src/main/java/team/incube/gsmc/v2/global/config/PropertiesScanConfig.java
  src/main/java/team/incube/gsmc/v2/global/config/RetryConfig.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/application/usecase/service/JwtIssueService.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/application/usecase/service/JwtParserService.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/data/JwtEnvironment.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/data/TokenDto.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/persistence/entity/RefreshTokenRedisEntity.java
  src/main/java/team/incube/gsmc/v2/global/security/jwt/persistence/repository/RefreshTokenRedisRepository.java
  src/main/java/team/incube/gsmc/v2/global/thirdparty/aws/data/AwsEnvironment.java
Labels: 💾 일반배포

#175 2025/06/30 20차 배포
  .github/workflows/auto-deploy-pr.yml
Labels: 💾 일반배포

#177 정기배포 자동생성 Action 스크립트에서 요약 생성 부분 정리
  .github/workflows/auto-deploy-pr.yml
Labels: 🛠️ 리팩터링, 🏭 CI/CD
