Repository team-incube/GSMC-server-V2, pull requests merged in 2025-04, with the labels that each got.

#27 CORS 에러 해결
  src/main/java/team/incude/gsmc/v2/global/security/config/CorsConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/config/SecurityConfig.java
Labels: 🔨 버그수정

#30 점수 관련 비즈니스 로직 서비스 클래스 테스트코드 작성
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/SimulateScoreService.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/SimulateScoreServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreServiceTest.java
Labels: ✨ 기능개발

#32 증빙자료 관련 persistence Port/Adapter 구현
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/EvidenceApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidenceApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/CreateActivityEvidenceUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/CreateOtherEvidenceUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/CreateReadingEvidenceUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/FindEvidenceByCurrentUserAndTypeUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/FindEvidenceByEmailAndFilteringTypeAndStatusUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/FindEvidenceByFilteringByEmailAndTitleAndTypeUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateActivityEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateOtherEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateReadingEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateReviewStatusUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/EvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
Labels: ✨ 기능개발

#33 증빙자료 관련 persistence Port/Adapter 수정
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/EvidenceApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidenceApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/FindEvidenceByFilteringByStudentCodeAndTitleAndTypeUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/FindEvidenceByStudentCodeAndFilteringTypeAndStatusUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
Labels: ✨ 기능개발

#34 현재 인증된 사용자 정보 조회 관련 변경 및 전체 점수 계산 클래스 구현
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/UpdateCurrentCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/CalculateTotalScoreUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreService.java
Labels: 🛠️ 리팩터링, ✨ 기능개발

#35 종합점수 계산 Aspect 구현 준비 및 ``StudentDetailJpaEntity`` 변경
  src/main/java/team/incude/gsmc/v2/aspect/log/HttpLoggingAspect.java
  src/main/java/team/incude/gsmc/v2/domain/member/domain/StudentDetail.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/entity/StudentDetailJpaEntity.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/CalculateTotalScoreUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/annotation/aspect/CalculateTotalScoreStduentCode.java
  src/main/java/team/incude/gsmc/v2/global/annotation/aspect/TriggerCalculateTotalScore.java
Labels: 🛠️ 리팩터링, ✨ 기능개발

#36 ``email``에서 ``studentCode``로 파라미터 변경 및 종합점수 계산 Aspect 구현
  src/main/java/team/incude/gsmc/v2/aspect/score/TotalScoreCalculateAspect.java
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignUpService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/MemberPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/MemberPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/ScoreApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScoreApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/FindScoreUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/UpdateScoreUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/presentation/ScoreWebAdapter.java
  src/main/java/team/incude/gsmc/v2/global/annotation/aspect/CalculateTotalScoreStudentCode.java
Labels: 🛠️ 리팩터링, ✨ 기능개발

#37 종합 점수 산출 이벤트 구현
  src/main/java/team/incude/gsmc/v2/aspect/score/TotalScoreCalculateAspect.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/ScoreApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScoreApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/SimulateScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/presentation/ScoreWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/presentation/data/request/GetScoreSimulateRequest.java
  src/main/java/team/incude/gsmc/v2/global/annotation/aspect/CalculateTotalScoreStudentCode.java
  src/main/java/team/incude/gsmc/v2/global/annotation/aspect/TriggerCalculateTotalScore.java
  src/main/java/team/incude/gsmc/v2/global/config/AspectConfig.java
  src/main/java/team/incude/gsmc/v2/global/config/SchedulerConfig.java
  src/main/java/team/incude/gsmc/v2/global/event/ScoreUpdatedEvent.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/ScoreUpdatedEventListener.java
  src/main/java/team/incude/gsmc/v2/global/util/SimulateScoreUtil.java
Labels: ✨ 기능개발

#38 점수 계산 이벤트 발행 방법 문서 갱신 및 인증제 점수 관련 비즈니스 로직 마이그레이션
  docs/Score-Updated-Event.adoc
  docs/Score-Updated-Event.md
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreService.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/FindScoreServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/score/application/usecase/service/UpdateScoreServiceTest.java
Labels: 🛠️ 리팩터링, 📃 문서화

#40 인증 관련 로직 오류수정 및 자격증 관련 API 테스트 코드 작성
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/CertificateApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificateApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificatePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/DeleteCertificateUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/FindCertificateUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/CertificateWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/CertificatePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/auth/CustomUserDetails.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/auth/CustomUserDetailsService.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/usecase/service/CurrentMemberProvider.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/usecase/service/FileDeleteService.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/aws/s3/usecase/service/FileUploadService.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateByEmailServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/UpdateCurrentCertificateServiceTest.java
Labels: ✨ 기능개발, 🔨 버그수정

#43 자격증 생성/삭제 로직 누락 문제 수정 및 코드 컨벤션 변경사항 반영
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/CertificateApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificateApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/FindCertificateUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateService.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/CertificateWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/request/CreateCertificateRequest.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/request/PatchCertificateRequest.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persentation/data/response/GetCertificateResponse.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/FindCertificateServiceTest.java
Labels: 🛠️ 리팩터링, 🔨 버그수정

#44 RDB 및 Redis 환경 변수 추가
  .env.example
  .github/workflows/deploy-dev.yml
  src/main/resources/application-dev.yaml
Labels: 🏭 CI

#42 스프레드시트 출력 기능 구현
  build.gradle.kts
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/usecase/service/SimulateScoreService.java
  src/main/java/team/incude/gsmc/v2/domain/score/domain/Category.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/entity/CategoryJpaEntity.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/mapper/CategoryMapper.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/SheetApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/port/SheetApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/usecase/GetSheetUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetService.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/domain/InMemoryMultipartFile.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/domain/constant/CategoryArea.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/presentation/SheetWebAdapter.java
  src/main/java/team/incude/gsmc/v2/global/event/handler/ScoreUpdatedEventListener.java
  src/main/java/team/incude/gsmc/v2/global/util/SimulateScoreUtil.java
Labels: ✨ 기능개발

#47 자격증 등록/삭제 로직 테스트코드 개선
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateServiceTest.java
Labels: 🛠️ 리팩터링

#49 Prometheun 메트릭 수집 시스템 구축
  build.gradle.kts
  compose.yaml
  docs/Grafana-Metrics-Dashboard-Guide.adoc
  prometheus/prometheus.yml
  src/main/java/team/incude/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/auth/filter/JwtAuthenticationFilter.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/application.yml
Labels: ✨ 기능개발, 🏭 CI

#46 학급 별 스프레드시트 생성 API 리팩터링 및 테스트코드 작성
  src/main/java/team/incude/gsmc/v2/domain/score/exception/InvalidCategoryException.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetService.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/exception/GenerationSheetFailedException.java
  src/main/java/team/incude/gsmc/v2/global/error/ErrorCode.java
  src/test/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetServiceTest.java
Labels: 🛠️ 리팩터링, ✨ 기능개발

#50 CorsConfig 커스텀 작성 및 Auth 테스트코드 작성
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailService.java
  src/main/java/team/incude/gsmc/v2/global/security/config/CorsConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/config/SecurityConfig.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/application/usecase/EmailSendUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/application/usecase/service/EmailSendService.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/config/EmailConfig.java
  src/main/resources/application-dev.yaml
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/RefreshServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignInServiceTest.java
Labels: ✨ 기능개발

#51 인증제 항목 조회 메서드에 캐싱 적용
  .env.example
  build.gradle.kts
  docs/Caching-Strategy-Guide.adoc
  docs/Score-Updated-Event-Guide.adoc
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/CategoryPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/global/config/CacheConfig.java
  src/main/resources/application.yaml
Labels: 🛠️ 리팩터링, 📃 문서화

#53 2025/04/24 5차 배포
  .env.example
  build.gradle.kts
  compose.yaml
  docs/Caching-Strategy-Guide.adoc
  docs/Grafana-Metrics-Dashboard-Guide.adoc
  docs/Score-Updated-Event-Guide.adoc
  prometheus/prometheus.yml
  src/main/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailService.java
  src/main/java/team/incude/gsmc/v2/domain/score/exception/InvalidCategoryException.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/CategoryPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetService.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/exception/GenerationSheetFailedException.java
  src/main/java/team/incude/gsmc/v2/global/config/CacheConfig.java
  src/main/java/team/incude/gsmc/v2/global/error/ErrorCode.java
  src/main/java/team/incude/gsmc/v2/global/security/config/CorsConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/config/SecurityConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/application/usecase/EmailSendUseCase.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/application/usecase/service/EmailSendService.java
  src/main/java/team/incude/gsmc/v2/global/thirdparty/email/config/EmailConfig.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/application.yml
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/RefreshServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SendAuthenticationEmailServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/auth/application/usecase/service/SignInServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/certificate/application/usecase/service/DeleteCertificateServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetServiceTest.java
Labels: 💾 일반배포

#54 CORS 허용 헤더 와일드카드 적용
  src/main/java/team/incude/gsmc/v2/global/security/config/CorsConfig.java
Labels: 🔨 버그수정

#57 서버 작동확인 엔드포인트 추가구현
  src/main/java/team/incude/gsmc/v2/domain/health/HealthCheckWebAdapter.java
  src/main/java/team/incude/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
  src/main/java/team/incude/gsmc/v2/global/security/jwt/auth/filter/JwtAuthenticationFilter.java
Labels: ✨ 기능개발

#59 학생 사용자 전체 조회/검색 API 구현
  src/main/java/team/incude/gsmc/v2/domain/member/application/MemberApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/MemberApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/FindAllStudentUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/SearchStudentUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/service/FindAllStudentService.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/usecase/service/SearchStudentService.java
  src/main/java/team/incude/gsmc/v2/domain/member/domain/StudentDetailWithEvidence.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/mapper/StudentDetailMapper.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/projection/StudentProjection.java
  src/main/java/team/incude/gsmc/v2/domain/member/presentation/MemberWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/presentation/data/response/GetStudentResponse.java
  src/main/java/team/incude/gsmc/v2/domain/member/presentation/data/response/SearchStudentResponse.java
  src/main/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetService.java
  src/test/java/team/incude/gsmc/v2/domain/sheet/application/usecase/service/GetSheetServiceTest.java
Labels: ✨ 기능개발

#60 증빙자료 관련 서비스 로직 변경
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByCurrentUserAndTypeService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByFilteringByStudentCodeAndTitleAndTypeService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByStudentCodeAndFilteringTypeAndStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateActivityEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherEvidenceByCurrentuserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherScoringEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReadingEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReviewStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/EvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/response/GetActivityEvidenceResponse.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/response/GetEvidencesResponse.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/response/GetOtherEvidenceResponse.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/response/GetReadingEvidenceResponse.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceServiceTest.java
Labels: ✨ 기능개발

#61 증빙자료 수정 서비스 로직 수정
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/EvidenceApplicationAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/EvidenceApplicationPort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateActivityEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateOtherEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/UpdateOtherScoringEvidenceByCurrentUserUseCase.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateActivityEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherEvidenceByCurrentuserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherScoringEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/EvidenceWebAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchActivityEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchOtherEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchOtherScoringEvidenceRequest.java
Labels: ✨ 기능개발

#63 AWS S3 관련 ``application-dev.yml`` 파일 환경변수 수정
  src/main/resources/application-dev.yaml
Labels: ✨ 기능개발, 📃 문서화

#65 AWS S3 REGION 환경변수로 수정 및 기본 값 추가
  src/main/resources/application-dev.yaml
Labels: ✨ 기능개발

#66 증빙자료 관련 서비스 클래스 로직 수정 및 요청 dto `@Size` 어노테이션 추가
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ActivityEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/OtherEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/port/ReadingEvidencePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/DeleteEvidenceService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByCurrentUserAndTypeService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByFilteringByStudentCodeAndTitleAndTypeService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/FindEvidenceByStudentCodeAndFilteringTypeAndStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateActivityEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherEvidenceByCurrentuserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateOtherScoringEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReadingEvidenceByCurrentUserService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/UpdateReviewStatusService.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/CreateActivityEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/CreateReadingEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchActivityEvidenceRequest.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/presentation/data/request/PatchReadingEvidenceRequest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateActivityEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceServiceTest.java
  src/test/java/team/incude/gsmc/v2/domain/evidence/application/usecase/service/CreateReadingEvidenceServiceTest.java
Labels: 🛠️ 리팩터링, ✨ 기능개발, 🔨 버그수정

#67 쿼리 메서드 스타일링 및 성능 최적화
  log/README.mdx
  src/main/java/team/incude/gsmc/v2/domain/certificate/application/port/CertificatePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/certificate/persistence/CertificatePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ActivityEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/EvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/OtherEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/evidence/persistence/ReadingEvidencePersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/MemberPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/MemberPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incude/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incude/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
Labels: 🛠️ 리팩터링
