Repository team-incube/GSMC-server-V2, pull requests merged in 2025-07, with the labels that each got.

#181 실제 RDB와 JPA Entity의 제약조건 통일
  src/main/java/team/incube/gsmc/v2/domain/member/persistence/entity/HomeroomTeacherDetailJpaEntity.java
  src/main/java/team/incube/gsmc/v2/domain/member/persistence/entity/StudentDetailJpaEntity.java
  src/main/java/team/incube/gsmc/v2/domain/score/persistence/entity/CategoryJpaEntity.java
Labels: 🛠️ 리팩터링

#179 정기배포 Pull Request 자동생성 Action 사용 권한 변경
  .github/workflows/auto-deploy-pr.yml
Labels: 🛠️ 리팩터링, 🏭 CI/CD

#184 증빙자료 임시 저장 응답 dto 생성자 생성 시 순서 문제 해결
  src/main/java/team/incube/gsmc/v2/domain/evidence/application/usecase/service/FindDraftEvidenceByCurrentUserService.java
Labels: 🔨 버그수정

#182 2025/07/03 21차 배포
  .github/ISSUE_TEMPLATE/Bug.md
  .github/workflows/auto-deploy-pr.yml
  docs/Grafana-Metrics-Dashboard-Guide.adoc
  src/main/java/team/incube/gsmc/v2/domain/evidence/application/usecase/service/FindDraftEvidenceByCurrentUserService.java
  src/main/java/team/incube/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/member/persistence/entity/HomeroomTeacherDetailJpaEntity.java
  src/main/java/team/incube/gsmc/v2/domain/member/persistence/entity/StudentDetailJpaEntity.java
  src/main/java/team/incube/gsmc/v2/domain/score/persistence/entity/CategoryJpaEntity.java
  src/main/java/team/incube/gsmc/v2/global/event/handler/FileUploadEventListener.java
  src/main/java/team/incube/gsmc/v2/global/event/handler/ScoreUpdatedEventListener.java
Labels: 💾 일반배포

#185 image 필드명 imageUri로 변경
  src/main/java/team/incube/gsmc/v2/domain/evidence/presentation/data/response/GetDraftActivityEvidenceResponse.java
Labels: 🔨 버그수정

#190 전체 학생 사용자에 대한 엑셀 시트 반환 API 구현
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/SheetApplicationAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/port/SheetApplicationPort.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/usecase/GetAllSheetUseCase.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetAllSheetService.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/presentation/SheetWebAdapter.java
  src/main/java/team/incube/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
  src/test/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetAllSheetServiceTest.java
Labels: ✨ 기능개발

#191 2025/07/08 22차 배포
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/service/FindScoreService.java
  src/main/java/team/incube/gsmc/v2/domain/score/presentation/data/GetScoreDto.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/SheetApplicationAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/port/SheetApplicationPort.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/usecase/GetAllSheetUseCase.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetAllSheetService.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/presentation/SheetWebAdapter.java
  src/main/java/team/incube/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
  src/main/java/team/incube/gsmc/v2/global/util/ScoreCalculatorUtil.java
  src/test/java/team/incube/gsmc/v2/domain/score/application/usecase/service/FindScoreServiceTest.java
  src/test/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetAllSheetServiceTest.java
Labels: 💾 일반배포

#192 상용환경 CD 스크립트 작성 및 기존 스크립트 개선
  .github/workflows/CD-dev.yml
  .github/workflows/CD-prod.yml
  .github/workflows/CI.yml
  .github/workflows/auto-deploy-pr.yml
  .github/workflows/test-develop.yml
Labels: 🏭 CI/CD

#193 개발환경 CD 시 무조건 실패 문제 수정
  .github/workflows/CD-dev.yml
  docker-compose.test.yaml
Labels: 🏭 CI/CD

#194 Mail username, password 기본값 제거
  src/main/resources/application-dev.yaml
Labels: 🛠️ 리팩터링

#201 자격증 서비스 클래스에서 잘못된 파라미터 전달 문제 수정
  src/main/java/team/incube/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
Labels: 🐞 버그

#200 인증제 항목명 불일치 문제 수정
  src/main/java/team/incube/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateService.java
  src/main/java/team/incube/gsmc/v2/domain/evidence/application/usecase/service/CreateOtherScoringEvidenceService.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/ScoreApplicationAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/port/ScoreApplicationPort.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/SimulateScoreUseCase.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/service/SimulateScoreService.java
  src/main/java/team/incube/gsmc/v2/domain/score/presentation/ScoreWebAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/score/presentation/data/request/GetScoreSimulateRequest.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetAllSheetService.java
  src/main/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetSheetService.java
  src/main/java/team/incube/gsmc/v2/global/util/ScoreCalculatorUtil.java
  src/main/java/team/incube/gsmc/v2/global/util/SimulateScoreUtil.java
  src/test/java/team/incube/gsmc/v2/domain/certificate/application/usecase/service/CreateCertificateServiceTest.java
  src/test/java/team/incube/gsmc/v2/domain/score/application/usecase/service/CalculateTotalScoreServiceTest.java
  src/test/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetAllSheetServiceTest.java
  src/test/java/team/incube/gsmc/v2/domain/sheet/application/usecase/service/GetSheetServiceTest.java
Labels: 🔨 버그수정

#204 유저 총점 백분위수 반환 로직 구현
  src/main/java/team/incube/gsmc/v2/domain/score/application/ScoreApplicationAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/port/ScoreApplicationPort.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/port/ScorePersistencePort.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/GetStudentPercentInClassUseCase.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/GetStudentPercentInGradeUseCase.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/service/GetStudentPercentInClassService.java
  src/main/java/team/incube/gsmc/v2/domain/score/application/usecase/service/GetStudentPercentInGradeService.java
  src/main/java/team/incube/gsmc/v2/domain/score/domain/constant/PercentileType.java
  src/main/java/team/incube/gsmc/v2/domain/score/exception/StudentClassMismatchException.java
  src/main/java/team/incube/gsmc/v2/domain/score/persistence/ScorePersistenceAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/score/presentation/ScoreWebAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/score/presentation/data/response/GetStudentPercentResponse.java
  src/main/java/team/incube/gsmc/v2/global/error/ErrorCode.java
  src/main/java/team/incube/gsmc/v2/global/security/config/DomainAuthorizationConfig.java
  src/test/java/team/incube/gsmc/v2/domain/score/application/usecase/service/GetStudentPercentInClassServiceTest.java
  src/test/java/team/incube/gsmc/v2/domain/score/application/usecase/service/GetStudentPercentInGradeServiceTest.java
Labels: ✨ 기능개발

#206 학생 검색 API에 정렬 기능 추가
  src/main/java/team/incube/gsmc/v2/domain/member/application/MemberApplicationAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/member/application/port/MemberApplicationPort.java
  src/main/java/team/incube/gsmc/v2/domain/member/application/port/StudentDetailPersistencePort.java
  src/main/java/team/incube/gsmc/v2/domain/member/application/usecase/SearchStudentUseCase.java
  src/main/java/team/incube/gsmc/v2/domain/member/application/usecase/service/SearchStudentService.java
  src/main/java/team/incube/gsmc/v2/domain/member/domain/constant/MemberSortDirection.java
  src/main/java/team/incube/gsmc/v2/domain/member/persistence/StudentDetailPersistenceAdapter.java
  src/main/java/team/incube/gsmc/v2/domain/member/presentation/MemberWebAdapter.java
  src/test/java/team/incube/gsmc/v2/domain/member/application/usecase/service/SearchStudentServiceTest.java
Labels: ✨ 기능개발
